<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>0bfa9e2b-7988-4456-9ee6-064a3c7f869d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;metronic&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kt_header_user_menu_toggle']/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>27dfc635-b5b0-440a-a41e-20002b7390b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/media/avatars/300-1.jpg</value>
      <webElementGuid>75d1a25e-c61f-45c0-8ae9-bd3800599746</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>metronic</value>
      <webElementGuid>557b6a96-43fa-45fb-9ca7-2c050d8fd785</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_header_user_menu_toggle&quot;)/div[@class=&quot;cursor-pointer symbol symbol-30px symbol-md-40px&quot;]/img[1]</value>
      <webElementGuid>6ca864a5-b5b4-47ec-9973-9d39263abe20</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_header_user_menu_toggle']/div/img</value>
      <webElementGuid>dec69a53-f4ee-4454-b887-f1b6a66dd37c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='metronic']</value>
      <webElementGuid>35be1f10-5913-4305-bcd8-1065eb4efcc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>e95d295b-0e76-4c56-9e9f-ab9bbe8794b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/media/avatars/300-1.jpg' and @alt = 'metronic']</value>
      <webElementGuid>8281c323-3b2c-4c09-b1e3-b38cfcd8cf4c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
