<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>a22a82a9-1e51-4605-a34f-ad67da1087f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;metronic&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kt_header_user_menu_toggle']/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f918385d-5386-4bec-82f7-626b1dc2f299</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/media/avatars/300-1.jpg</value>
      <webElementGuid>0aba0113-c7e8-4a74-85de-b323678cf583</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>metronic</value>
      <webElementGuid>345aab37-d4ca-485c-9733-03022358686a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_header_user_menu_toggle&quot;)/div[@class=&quot;cursor-pointer symbol symbol-30px symbol-md-40px&quot;]/img[1]</value>
      <webElementGuid>359f4c31-892f-427d-8ac6-0b66692121a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_header_user_menu_toggle']/div/img</value>
      <webElementGuid>428ae29e-ac9f-45c5-9a7f-9ca80f0fc306</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='metronic']</value>
      <webElementGuid>a1b75b7b-2bcc-45ad-b116-603f05171279</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>abb07244-307a-4edf-91d3-5555be4094e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/media/avatars/300-1.jpg' and @alt = 'metronic']</value>
      <webElementGuid>4fdabab0-b1a0-45bb-a58e-142f4b82b470</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
