<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Forgot your Password</name>
   <tag></tag>
   <elementGuidId>580ee4b3-9b9d-441c-9445-41c223cbdbbc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.link-primary.fw-bold.ms-13</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='kt_login_signin_form']/div[3]/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6ef1e1bb-4e60-433c-a298-9eea96cefc40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>link-primary fw-bold ms-13</value>
      <webElementGuid>aec02382-15de-4a47-bcba-518e3daba585</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/auth/forgot-password</value>
      <webElementGuid>674c566d-96e5-420f-8182-8bef207dae45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Forgot your Password ?</value>
      <webElementGuid>ca50963d-629a-431a-a904-e077da1f7c0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_login_signin_form&quot;)/div[@class=&quot;fv-row mb-10&quot;]/div[@class=&quot;position-relative mb-3&quot;]/a[@class=&quot;link-primary fw-bold ms-13&quot;]</value>
      <webElementGuid>76b41846-85a6-4eee-8b74-de4b40a734b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='kt_login_signin_form']/div[3]/div[2]/a</value>
      <webElementGuid>ebc2e208-3bd9-4492-887f-5258975e9dbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Forgot your Password ?')]</value>
      <webElementGuid>c3db18d0-ddf9-4ee3-9118-63bd565249ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::a[1]</value>
      <webElementGuid>4d4b22d5-ed2e-4d3e-a828-9a877e30df9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/following::a[1]</value>
      <webElementGuid>cac43386-7d02-4689-96e1-9c1d391b1343</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SIGN IN'])[1]/preceding::a[1]</value>
      <webElementGuid>8edfa59c-f084-4ada-9ce6-1652121d6792</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Organize your Investments'])[1]/preceding::a[2]</value>
      <webElementGuid>bdfcf286-18c9-4c72-8a73-0c4075d64de7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Forgot your Password ?']/parent::*</value>
      <webElementGuid>6d175da4-24ef-4d8b-97da-8dfacd7ee845</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/auth/forgot-password')]</value>
      <webElementGuid>f731f721-3126-4dcd-9006-aa6138481271</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>5ab974c4-f6ba-44e3-a66f-b86d49df6ffe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/auth/forgot-password' and (text() = 'Forgot your Password ?' or . = 'Forgot your Password ?')]</value>
      <webElementGuid>f9f64eef-07be-4dd3-ba47-1557a90436a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
