<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Password reset is sent. Please check yo_7b6fc3</name>
   <tag></tag>
   <elementGuidId>4bb642a1-5349-4aa4-a0b5-36dc6e949361</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.text-primary.fw-bold.mb-5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='kt_login_password_reset_form']/div/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>31eb554c-7ef0-43cb-ade2-71b08559da3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-primary fw-bold mb-5</value>
      <webElementGuid>668a2792-65a5-4457-a297-4549d284b3fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>alert</value>
      <webElementGuid>37379b94-afa9-477b-bb08-e559d6b2371d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Password reset is sent. Please check your email</value>
      <webElementGuid>453c4d6e-0481-439d-87f6-acc0f6e6028e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_login_password_reset_form&quot;)/div[@class=&quot;text-center&quot;]/div[@class=&quot;fv-plugins-message-container&quot;]/div[@class=&quot;text-primary fw-bold mb-5&quot;]</value>
      <webElementGuid>254dfa4f-2cd8-4c0d-b528-e553048fbfb7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='kt_login_password_reset_form']/div/div[2]/div</value>
      <webElementGuid>a9715c95-6fed-4b53-b376-fd99bbff1f89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter the email you used when you joined to reset password'])[1]/following::div[2]</value>
      <webElementGuid>fce4387e-d368-448e-aec0-a440b3c7e374</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot Password ?'])[1]/following::div[3]</value>
      <webElementGuid>a65059ac-e006-44ac-b9b5-77cb1b509ddc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/preceding::div[1]</value>
      <webElementGuid>880495ee-6466-4dfa-bc66-daebe2410d78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/preceding::div[2]</value>
      <webElementGuid>4e8a263d-3a0e-4f41-9ee0-fd5815c76b38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Password reset is sent. Please check your email']/parent::*</value>
      <webElementGuid>55a295ad-2680-499d-a5f8-2933190ddb4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]/div</value>
      <webElementGuid>b4cbef91-1710-4225-819c-1b5d865c4bf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Password reset is sent. Please check your email' or . = 'Password reset is sent. Please check your email')]</value>
      <webElementGuid>9489319d-dafd-42c3-810a-9506d97f80ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
